pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "npm install"
            }
        }

        stage('Test') {
            steps {
                sh "npm test || true"
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    pm2 delete express-frontend || true
                    pm2 start app.js --name express-frontend
                    pm2 save
                """
            }
        }
    }

    post {
        success {
            echo 'Express deployment successful!'
        }
        failure {
            echo 'Express deployment failed.'
        }
    }
}
