pipeline {
    agent any

    environment {
        REPO_DIR = "/home/ubuntu/flask-express-cicd-jenkins-github-webhooks-aws-ec2"
        APP_DIR  = "${REPO_DIR}/express-frontend"
    }

    stages {
        stage('Checkout') {
            steps {
                dir("${REPO_DIR}") {
                    git branch: 'main', url: 'https://github.com/shubhmate/flask-express-cicd-jenkins-github-webhooks-aws-ec2'
                }
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "cd ${APP_DIR} && npm install"
            }
        }

        stage('Test') {
            steps {
                sh "cd ${APP_DIR} && npm test || true"
            }
        }

        stage('Deploy') {
            steps {
                sh "pm2 restart express-frontend || pm2 start ${APP_DIR}/app.js --name express-frontend"
            }
        }
    }

    post {
        success {
            echo 'Express deployment successful!'
        }
        failure {
            echo 'Express deployment failed.'
        }
    }
}
