pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                cleanWs()
                checkout scm
            }
        }

        stage('Install Dependencies') {
            steps {
                sh "cd ${WORKSPACE}/express-frontend && npm install"
            }
        }

        stage('Test') {
            steps {
                sh "cd ${WORKSPACE}/express-frontend && npm test || true"
            }
        }

        stage('Deploy') {
            steps {
                sh """
                    sudo -u ubuntu pm2 delete express-frontend || true
                    sudo -u ubuntu pm2 start ${WORKSPACE}/express-frontend/app.js --name express-frontend
                    sudo -u ubuntu pm2 save
                """
            }
        }
    }

    post {
        success {
            echo 'Express deployment successful!'
        }
        failure {
            echo 'Express deployment failed.'
        }
    }
}
